/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:45:45 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

//#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIGestureRecognizer.h>

@class NSArray, NSMutableSet;

@interface UILongPressGestureRecognizer : UIGestureRecognizer {
	double _minimumPressDuration;
}

@property (assign,nonatomic) double minimumPressDuration; 

@end

