/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:51:21 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableArray;

@interface SBIconContentView : UIView {

	long long _orientation;
	NSMutableArray* _folderContentViews;

}

@property (assign,nonatomic) long long orientation;              //@synthesize orientation=_orientation - In the implementation block
-(void)clearAllFolderContentViews;
-(void)pushFolderContentView:(id)arg1 ;
-(void)updateLayoutWithDuration:(double)arg1 ;
-(CGRect)_frameForFolderView:(id)arg1 ;
-(void)popFolderContentView:(id)arg1 ;
-(id)_folderViews;
-(void)dealloc;
-(void)layoutSubviews;
-(long long)orientation;
-(void)didAddSubview:(id)arg1 ;
-(void)setOrientation:(long long)arg1 ;
-(id)initWithOrientation:(long long)arg1 ;
@end

