/*
 * This header is generated by weak_classdump 0.2
 * on Monday, May 5, 2014 at 5:41:38 PM Eastern Daylight Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import "PSRootController.h"

@interface PrefsRootController : PSRootController {
//	PrefsListController* _rootListController; 
}

+(void)playRingtoneWithIdentifier:(id)arg1 loop:(_Bool)arg2;
-(void)mediaServerDiedNotification:(id)arg1;
-(void)setupControllerForToolbar:(id)arg1;
-(void)pushViewController:(id)arg1 animated:(_Bool)arg2;
-(void)setViewControllers:(id)arg1 animated:(_Bool)arg2;
-(void)pushViewController:(id)arg1 transition:(int)arg2;
-(void)dealloc;
-(void)loadView;
-(id)initWithTitle:(id)arg1 identifier:(id)arg2;
-(id)rootListController;
@end