/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"
#import "PSTextView.h"
#import <UIKit/UIKit.h>

@interface PSTextViewTableCell : PSTableCell <UITextViewDelegate> {
    PSTextView *_textView;
}

@property(retain) PSTextView *textView;

- (void)_adjustTextView:(id)arg1 updateTable:(BOOL)arg2 withSpecifier:(id)arg3;
- (BOOL)becomeFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)cellRemovedFromView;
- (void)dealloc;
- (void)drawTitleInRect:(CGRect)arg1 selected:(BOOL)arg2;
- (id)initWithStyle:(UITableViewCellStyle)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)layoutSubviews;
- (BOOL)resignFirstResponder;
- (void)setTextView:(PSTextView *)arg1;
- (void)setValue:(id)arg1;
- (void)textContentViewDidChange:(id)arg1;
- (void)textContentViewDidEndEditing:(id)arg1;
- (PSTextView *)textView;

@end