/*
 * This header is generated by weak_classdump 0.2
 * on Monday, May 5, 2014 at 5:41:41 PM Eastern Daylight Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIKit/UIKit.h>
// #import <EAAccessoryDelegate.h>
// #import <MCProfileConnectionObserver.h>

@interface PreferencesAppController : UIApplication <UIApplicationDelegate> //, EAAccessoryDelegate, MCProfileConnectionObserver> {
	/*
	PSSplitViewController* _splitViewController; 
	PrefsRootController* _controller; 
	UIWindow* _window; 
	_Bool _isLocked; 
	NSMutableSet* _busyControllers; 
	_Bool _dontSelectGeneralOnLaunch; 
	_Bool _loadingExternalURL; 
	unsigned long long _backgroundTaskHandle; 
	double _timeoutLimit; 
	_Bool _settingsWasResigned; 
	unsigned _rootDomainConnect; 
	unsigned _pmNotifier; 
	struct IONotificationPort* _systemPowerPortRef; 
	struct __CFRunLoopSource* _pmSource; 
	EAAccessory* _speakerAccessory; 
}*/

//@property (assign) unsigned rootDomainConnect; 				//@synthesize rootDomainConnect=_rootDomainConnect - In the implementation block
//@property (assign) _Bool dontSelectGeneralOnLaunch; 				//@synthesize dontSelectGeneralOnLaunch=_dontSelectGeneralOnLaunch - In the implementation block
//@property (nonatomic,retain) UIWindow* window; 
-(void)_registerForPowerNotifications;
-(void)systemDidWake:(id)arg1;
-(void)updateSoftwareUpdateBadgeOnSpecifier:(id)arg1;
-(id)oneTimeJumpURL;
-(void)processURL:(id)arg1;
-(void)_handleBusyControllers;
-(void)clearControllersForSuspendedState;
-(void)generateURL;
-(id)keyValueDictionaryForURL:(id)arg1;
-(void)_deregisterForPowerNotifications;
-(void)setDontSelectGeneralOnLaunch:(_Bool)arg1;
-(void)addBusyControllersFromRootController:(id)arg1;
-(void)_suspendControllers;
-(void)_resetSnapshotImage;
-(void)endAndInvalidateBackgroundTask;
-(void)stopPlayback;
-(void)_handleExternalApplicationChange;
-(void)accessoryDidDisconnect:(id)arg1;
-(void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
-(void)profileConnectionDidReceivePasscodeChangedNotification:(id)arg1 userInfo:(id)arg2;
-(void)profileConnectionDidReceiveProfileListChangedNotification:(id)arg1 userInfo:(id)arg2;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
-(void)dealloc;
-(void)applicationWillTerminate:(id)arg1;
-(void)applicationDidBecomeActive:(id)arg1;
-(void)applicationWillResignActive:(id)arg1;
-(void)applicationDidEnterBackground:(id)arg1;
-(void)applicationWillEnterForeground:(id)arg1;
-(_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
-(void)applicationWillSuspendForEventsOnly;
-(void)applicationDidResumeForEventsOnly;
-(double)defaultImageSnapshotExpiration;
-(void)applicationOpenURL:(id)arg1;
-(void)userDefaultsDidChange:(id)arg1;
-(void)significantTimeChange;
-(_Bool)runTest:(id)arg1 options:(id)arg2;
-(void)_accessoryDidConnect:(id)arg1;
-(void)setRootDomainConnect:(unsigned)arg1;
-(id)rootController;
-(void)controllerFinished:(id)arg1;
-(id)appWindow;
-(void)resetLocale;
@end