/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:46:21 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct BTDeviceImpl* BTDeviceImplRef;

typedef struct _NSZone* NSZoneRef;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
} SCD_Struct_Bl2;

typedef struct BTLocalDeviceImpl* BTLocalDeviceImplRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTDiscoveryAgentImpl* BTDiscoveryAgentImplRef;

typedef struct BTPairingAgentImpl* BTPairingAgentImplRef;

typedef struct BTAccessoryManagerImpl* BTAccessoryManagerImplRef;

